 const GenomesDataActionType = {
    FETCH_GENOMES_DATA_START : 'FETCH_GENOMES_DATA_START',
    FETCH_GENOMES_DATA_SUCCESS : 'FETCH_GENOMES_DATA_SUCCESS',
    FETCH_GENOMES_DATA_FAILURE : 'FETCH_GENOMES_DATA_FAILURE',
}

export default GenomesDataActionType;